### ISSUE TITLE
Faced PicklingError 

### ISSUE THREAD

**Issue by qkfxhqrkrrl** [chibohe/CdistNet-pytorch#4]
```
2022-02-02 16:31:18,549 [INFO ]  dataset_root:    root\is\here
         dataset: \
sub-directory:  /.       num samples: 3736
num total samples of total dataset is 3736


2022-02-02 16:31:18,559 [INFO ]  num total samples of \: 3736 x 1.0 (total_data_usage_ratio) = 3736
num samples of \ per batch: 32 x 1.0 (batch_ratio) = 32

Traceback (most recent call last):
  File "train.py", line 71, in <module>
    main()
  File "train.py", line 48, in main
    train_loader = build_data_loader(flags, mode='train')
  File "root\is\here\CdistNet2\program.py", line 84, in build_data_loader
    dataloader = create_module(dataloader_infor)(flags)
  File "root\is\here\CdistNet2\dataset.py", line 114, in __init__
    self.dataloader_iter_list.append(iter(_data_loader))
  File "I:\Anaconda\envs\CDistNet2\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "I:\Anaconda\envs\CDistNet2\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "I:\Anaconda\envs\CDistNet2\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "I:\Anaconda\envs\CDistNet2\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "I:\Anaconda\envs\CDistNet2\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "I:\Anaconda\envs\CDistNet2\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "I:\Anaconda\envs\CDistNet2\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'flags.FLAGS'>: attribute lookup FLAGS on flags failed

(CDistNet2) I:\Google_Drive\Hyundai\Learnin\CdistNet2>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "I:\Anaconda\envs\CDistNet2\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "I:\Anaconda\envs\CDistNet2\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```
I don't know what is problem exactly but Looks like [problem of namedtuple](https://stackoverflow.com/questions/4677012/python-cant-pickle-type-x-attribute-lookup-failed) I guess??  
Is there any way to get around this problem?

**Comment by webbrain-one** [comment]
Thanks for the detailed report! I've opened PR #7 (https://github.com/chibohe/CdistNet-pytorch/pull/7) to fix this. It addresses the `PicklingError` by making the `flags`/config object picklable before it's passed into the dataset/DataLoader, which lets the Windows multiprocessing workers start correctly.
